name: Squirrel_Client CI

on:
  pull_request:
    branches:
      - 'develop'
      - 'main'

jobs:
  Squirrel_Client_CI:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run Next.js build
      run: npm run build

    - name: Success Discord Notification
      uses: sarisia/actions-status-discord@v1.11.0
      if: ${{ success() }}
      with:
        webhook: ${{ secrets.WEBHOOK_CI }}
        title: "🎉 Squirrel Client CI"
        description: "CI success"
        status: ${{ job.status }}
        content: "CI 성공"
        username: Squirrel Client CI bot
        url: "https://github.com/Team-Ampersand/Squirrel-client"
        color: 4CAF50

    - name: Failure notification to discord
      uses: sarisia/actions-status-discord@v1.11.0
      if: failure()
      with:
        webhook: ${{ secrets.WEBHOOK_CI }}
        title: "❌ Squirrel Client CI"
        description: "CI failed"
        content: "안돼 안바꿔줘 돌아가"
        status: ${{ job.status }}
        username: Squirrel Client CI bot
        url: "https://github.com/Team-Ampersand/Squirrel-client"
        color: e74c3c
